name: 'Generate Checksum Files'
description: 'Generate checksums (SHA256) for multiple files'
branding:
  icon: 'activity'
  color: 'black'
inputs:
  pattern:
    description: 'Pattern to search for files (glob)'
    required: true
  checksum_extension:
    description: 'Checksum extension'
    required: false
  subfolder:
    description: 'Subfolder to put the checksum files'
    required: false
  paths_ignore:
    description: 'Paths to ignore'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.pattern }}'
    - '${{ inputs.checksum_extension }}'
    - '${{ inputs.subfolder }}'
    - '${{ inputs.paths_ignore }}'
