name: 'Generate Checksum Files'
description: 'Generate checksums (SHA256) for multiple files'
branding:
  icon: 'activity'
  color: 'black'
inputs:
  pattern:
    description: 'Pattern to search for files (glob)'
    required: true
  suffix:
    description: 'Suffix for the checksum files'
    required: false
    default: 'checksum'
  subfolder:
    description: 'Subfolder to put the checksum files'
    required: false
    default: ''
  paths_ignore:
    description: 'Paths to ignore'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.pattern }}'
    - '${{ inputs.suffix }}'
    - '${{ inputs.subfolder }}'
    - '${{ inputs.paths_ignore }}'
